### ISSUE TITLE
I like the UI. how to remove all encryption ?

### ISSUE THREAD

**Issue by xkungxfu** [mxrcode/Retask#1]
I don't know why to use encryption. but it is a very beautiful task manager.

so, I want to remove encryptions.

thanks.

**Comment by mxrcode** [comment]
Hello there. 

Thank you for your interest in **TaskGuard**.

Although encryption is the main feature of the program, it is not mandatory. You can leave the password blank the first time you run **TaskGuard**, or delete it from the existing _user_data.db_ file.
_user_data.db_ File without password can be freely opened in such programs as _HeidiSQL_ and other sql editors.

![Untitled](https://github.com/mxrcode/TaskGuard/assets/123785508/85689aa1-7ec0-4b18-a08c-3edf38fa6b90)

Best Regards, 
@mxrcode

**Comment by xkungxfu** [comment]
got it! thank you very much.

I found another solution. I changed "QSQLITECIPHER" to "QSQLITE". and it seems all encryptions don't work more.
